### ISSUE TITLE
macos error m1

### ISSUE THREAD

**Issue by imtorich** [CCBlueX/LiquidLauncher#201]
Failed to launch client: Process exited with non-zero code: 1

>
[02:45:18] [Render thread/INFO]: Loading ultralight...
[02:45:18] [Render thread/INFO]: Checking resources...
[02:45:18] [Render thread/INFO]: Loading ultralight natives
[02:45:18] [Render thread/INFO]: Native path: /Users/anon/Library/Application Support/net.CCBlueX.LiquidLauncher/gameDir/nextgen/LiquidBounce/ultralight/bin
[02:45:18] [Render thread/ERROR]: Unable to load client.
java.lang.UnsatisfiedLinkError: Can't load library: /Users/anon/Library/Application Support/net.CCBlueX.LiquidLauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libglib-2.0-0.dylib
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:144) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:70) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:126) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:88) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:140) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$bhg000$liquidbounce$startClient(class_3
10.java:9087) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:631) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.14.21-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
Failed to launch client: Process exited with non-zero code: 1

**Comment by imtorich** [comment]
IM using 
java version "19.0.2" 2023-01-17
Java(TM) SE Runtime Environment (build 19.0.2+7-44)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)

on MacBook Air, M1

**Comment by imtorich** [comment]
Please fix it! Neither your launcher works on these versions, nor through manual installation with Fabric! I tried it on Windows now, it works there, but, I'm not comfortable with it!!!

**Comment by Razzy52** [comment]
Liquidlauncher doesn't work properly on macos
